dist: trusty

sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

env:
  global:
    - COMPOSER_NO_INTERACTION=1
    - WP_VERSION=*

matrix:
  include:
    - php: 5.3
      dist: precise
      env: TRAVIS_DIST_PRECISE=1
    - php: 7.2
      env: WP_MULTISITE=1
    - php: 7.2
      env: WP_VERSION=4.8
    - php: 7.2
      env: WP_VERSION=4.7 COVERAGE=1 DEV=1
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

before_install:
  # Install latest version of Node.js (https://github.com/creationix/nvm).
  - if [ "${TRAVIS_DIST_PRECISE}" == "1" ]; then nvm install node; fi
  # Create database for PHPUnit tests.
  - mysql -e 'CREATE DATABASE wp_phpunit_tests;'

install:
  # Install Grunt command line interface (https://github.com/gruntjs/grunt-cli).
  - npm install -g grunt-cli
  # Install Node.js packages.
  - npm install
  # Update Composer itself to the latest version (https://getcomposer.org/doc/03-cli.md#self-update-selfupdate-).
  - composer self-update
  # Validat composer.json file.
  - composer validate --strict
  # Install Composer packages.
  - composer install --no-dev
  # Test on specific WordPress version.
  - composer require --dev phpunit/phpunit johnpbloch/wordpress:${WP_VERSION} wp-phpunit/wp-phpunit:${WP_VERSION}
  - if [ "$DEV" == "1" ]; then composer install --dev; fi

script:
  - vendor/bin/phpunit
  - grunt phplint
  - if [ $DEV == "1" ]; then vendor/bin/phpcs . -v; fi

after_success:
  - if [ $COVERAGE == "1" ]; then php vendor/bin/coveralls -v; fi
  - if [ $COVERAGE == "1" ]; then bash <(curl -s https://codecov.io/bash); fi
